@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User inputs edit command;
:Parse edit command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid command])
    :Execute edit command;
    :Create instances of each field;
    :Updates edited person to AddressBook;
    :Display success message;
else ([else])
    :Display error message;
endif
stop
@enduml
