@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User inputs add command;
:Parse add command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([valid command])
    :Execute add command;
    :Edit person's details;
    :Save modified person in AddressBook;
    :Display success message;
else ([else])
    :Display error message;
endif
stop
@enduml
